services:
  intellij:
    container_name: docker-intellij
    restart: unless-stopped
    image: madduci/docker-intellij:2024.2.4-community
    build:
      context: ./
    environment:
      DISPLAY: "192.168.5.161:0.0"
    volumes:
      - user-data:/home/user/.config/JetBrains
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/user/.Xauthority

volumes:
  user-data: